import os
import re
import sqlite3
import threading
import time
from pathlib import Path


try:
    import psycopg  # type: ignore
except ImportError:  # pragma: no cover - optional dependency
    psycopg = None

try:
    import psycopg2  # type: ignore
except ImportError:  # pragma: no cover - optional dependency
    psycopg2 = None


POSTGRES_PREFIXES = ("postgres://", "postgresql://")
IDENTITY_TABLES = {"trade_history", "broker_connections"}
SQLITE_LOCK_MESSAGES = (
    "database is locked",
    "database table is locked",
    "database schema is locked",
    "cannot commit transaction - sql statements in progress",
)


def _database_url() -> str:
    return str(os.getenv("DATABASE_URL", "")).strip()


def using_postgres() -> bool:
    return _database_url().lower().startswith(POSTGRES_PREFIXES)


def database_backend_label() -> str:
    return "postgresql" if using_postgres() else "sqlite"


def sqlite_path(default_name: str = "finwise.db") -> str:
    configured = str(os.getenv("SQLITE_PATH", "")).strip()
    if configured:
        return configured
    return str(Path(default_name))


def _env_int(name: str, default: int, minimum: int = 0) -> int:
    try:
        value = int(str(os.getenv(name, default)).strip() or default)
    except (TypeError, ValueError):
        value = default
    return max(minimum, value)


def sqlite_busy_timeout_ms() -> int:
    return _env_int("SQLITE_BUSY_TIMEOUT_MS", 30000, 1000)


def sqlite_busy_retries() -> int:
    return _env_int("SQLITE_BUSY_RETRIES", 8, 0)


def is_database_locked_error(exc: Exception) -> bool:
    if not isinstance(exc, sqlite3.OperationalError):
        return False
    message = str(exc).lower()
    return any(fragment in message for fragment in SQLITE_LOCK_MESSAGES)


def _drain_cursor(raw_cursor) -> None:
    try:
        raw_cursor.fetchall()
    except Exception:
        pass


def is_integrity_error(exc: Exception) -> bool:
    if isinstance(exc, sqlite3.IntegrityError):
        return True
    if psycopg is not None:
        try:
            from psycopg.errors import IntegrityError as PsycopgIntegrityError  # type: ignore

            if isinstance(exc, PsycopgIntegrityError):
                return True
        except Exception:
            pass
    if psycopg2 is not None:
        try:
            from psycopg2 import IntegrityError as Psycopg2IntegrityError  # type: ignore

            if isinstance(exc, Psycopg2IntegrityError):
                return True
        except Exception:
            pass
    message = str(exc).lower()
    return "integrity" in message or "unique constraint" in message or "duplicate key" in message


class CompatCursor:
    def __init__(self, connection, raw_cursor):
        self.connection = connection
        self.raw_cursor = raw_cursor
        self.lastrowid = getattr(raw_cursor, "lastrowid", None)
        self._pending_rows = None

    def _translate_query(self, query: str) -> str:
        translated = query
        translated = re.sub(
            r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            translated,
            flags=re.IGNORECASE,
        )
        translated = translated.replace("?", "%s")
        return translated

    def execute(self, query: str, params=None):
        params = tuple(params or ())
        stripped = query.strip()
        upper = stripped.upper()
        self._pending_rows = None
        if not self.connection.is_postgres:
            self.connection._run_sqlite(lambda: self.raw_cursor.execute(query, params))
            if upper.startswith(("PRAGMA JOURNAL_MODE", "PRAGMA BUSY_TIMEOUT", "PRAGMA SYNCHRONOUS")):
                self.connection._run_sqlite(lambda: _drain_cursor(self.raw_cursor))
            self.lastrowid = getattr(self.raw_cursor, "lastrowid", None)
            return self

        pragma_match = re.match(r"PRAGMA\s+TABLE_INFO\(([^)]+)\)", stripped, flags=re.IGNORECASE)
        if upper.startswith("PRAGMA JOURNAL_MODE"):
            self.lastrowid = None
            return self
        if pragma_match:
            table_name = pragma_match.group(1).strip().strip("'\"")
            self.raw_cursor.execute(
                """
                SELECT
                    ordinal_position - 1 AS cid,
                    column_name,
                    data_type,
                    CASE WHEN is_nullable = 'YES' THEN 0 ELSE 1 END AS notnull,
                    column_default,
                    0 AS pk
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = %s
                ORDER BY ordinal_position
                """,
                (table_name,),
            )
            self._pending_rows = self.raw_cursor.fetchall()
            self.lastrowid = None
            return self

        translated = self._translate_query(query)
        self.raw_cursor.execute(translated, params)
        self.lastrowid = getattr(self.raw_cursor, "lastrowid", None)
        insert_match = re.match(r"\s*INSERT\s+INTO\s+([a-zA-Z_][\w]*)", query, flags=re.IGNORECASE)
        if insert_match:
            table_name = insert_match.group(1).lower()
            if table_name in IDENTITY_TABLES:
                try:
                    follow_cursor = self.connection.raw_connection.cursor()
                    follow_cursor.execute("SELECT LASTVAL()")
                    row = follow_cursor.fetchone()
                    self.lastrowid = row[0] if row else None
                    follow_cursor.close()
                except Exception:
                    self.lastrowid = None
        return self

    def fetchone(self):
        if self._pending_rows is not None:
            if not self._pending_rows:
                return None
            return self._pending_rows.pop(0)
        if not self.connection.is_postgres:
            return self.connection._run_sqlite(self.raw_cursor.fetchone)
        return self.raw_cursor.fetchone()

    def fetchall(self):
        if self._pending_rows is not None:
            rows = list(self._pending_rows)
            self._pending_rows = []
            return rows
        if not self.connection.is_postgres:
            return self.connection._run_sqlite(self.raw_cursor.fetchall)
        return self.raw_cursor.fetchall()

    def close(self):
        if not self.connection.is_postgres:
            return self.connection._run_sqlite(self.raw_cursor.close)
        return self.raw_cursor.close()


class CompatConnection:
    def __init__(self, raw_connection, *, is_postgres: bool):
        self.raw_connection = raw_connection
        self.is_postgres = is_postgres
        self._sqlite_lock = threading.RLock()

    def _run_sqlite(self, operation):
        retries = sqlite_busy_retries()
        delay = 0.08
        for attempt in range(retries + 1):
            try:
                with self._sqlite_lock:
                    return operation()
            except sqlite3.OperationalError as exc:
                if not is_database_locked_error(exc) or attempt >= retries:
                    raise
                time.sleep(min(delay * (attempt + 1), 1.5))

    def cursor(self):
        return CompatCursor(self, self.raw_connection.cursor())

    def execute(self, query: str, params=None):
        cursor = self.cursor()
        cursor.execute(query, params)
        return cursor

    def commit(self):
        if not self.is_postgres:
            return self._run_sqlite(self.raw_connection.commit)
        return self.raw_connection.commit()

    def rollback(self):
        if not self.is_postgres:
            return self._run_sqlite(self.raw_connection.rollback)
        return self.raw_connection.rollback()

    def close(self):
        if not self.is_postgres:
            return self._run_sqlite(self.raw_connection.close)
        return self.raw_connection.close()


def connect_database(default_sqlite_name: str = "finwise.db") -> CompatConnection:
    if using_postgres():
        database_url = _database_url()
        if psycopg is not None:
            raw_connection = psycopg.connect(database_url)
            return CompatConnection(raw_connection, is_postgres=True)
        if psycopg2 is not None:
            raw_connection = psycopg2.connect(database_url)
            return CompatConnection(raw_connection, is_postgres=True)
        raise RuntimeError(
            "DATABASE_URL is set for PostgreSQL, but no PostgreSQL driver is installed. "
            "Install psycopg[binary] or psycopg2-binary."
        )

    timeout_seconds = sqlite_busy_timeout_ms() / 1000
    raw_connection = sqlite3.connect(
        sqlite_path(default_sqlite_name),
        timeout=timeout_seconds,
        check_same_thread=False,
    )
    cursor = raw_connection.execute(f"PRAGMA busy_timeout={sqlite_busy_timeout_ms()};")
    _drain_cursor(cursor)
    cursor.close()
    try:
        cursor = raw_connection.execute("PRAGMA journal_mode=WAL;")
        _drain_cursor(cursor)
        cursor.close()
        cursor = raw_connection.execute("PRAGMA synchronous=NORMAL;")
        _drain_cursor(cursor)
        cursor.close()
    except sqlite3.OperationalError as exc:
        if not is_database_locked_error(exc):
            raise
    return CompatConnection(raw_connection, is_postgres=False)
